Update patch set 9
Patch Set 9: I would prefer that you didn't submit this; No score

I'm still getting WNFE on my Linux box while running the tests with the Helios platform.  I don't think the dialog is opening:

canCloneARemoteRepo(org.eclipse.egit.ui.wizards.clone.GitCloneWizardTest)  Time elapsed: 5.254 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find shell matching: with text 'Import'

The workbench seems to startup, just sits there, and then finally exits.  Seems to me that the import dialog doesn't start like expected, so all of the tests just time out and fail.

Patch-set: 9