Update patch set 6
Patch Set 6:

> no coverage on GitSynchronizeWizard and GitSynchronizeWizardPage

I'll add it after I fix issues in current test set

> java.lang.AssertionError: expected:<0> but was:<8>

This should never happen! Maybe on Windows we show files that should be ignored ... currently I don't bloody idea how this can happen.

> java.io.IOException: C:\test\junit-workspace\.git\logs\refs\heads in use or undeletable

This should be investigated, we should free resources before we'll delete it. It seams that I should install Windows and run tests also under this platform ...

Additionally on my Linux GitRepositoriesViewTest always fails with NPE listed in Error view:
Caused by: java.lang.NullPointerException
at org.eclipse.egit.ui.internal.clone.GitSelectRepositoryPage.checkPage(GitSelectRepositoryPage.java:179)
at org.eclipse.egit.ui.internal.clone.GitSelectRepositoryPage.access$2(GitSelectRepositoryPage.java:176)
at org.eclipse.egit.ui.internal.clone.GitSelectRepositoryPage$1.widgetSelected(GitSelectRepositoryPage.java:128)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1282)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1267)
at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1061)
at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot$2.run(AbstractSWTBot.java:159)
at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$5.doRun(UIThreadRunnable.java:221)
at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:89)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
... 51 more

Patch-set: 6