Update patch set 1
Patch Set 1: I would prefer that you didn't submit this

when toggling "Show all branches" this always throws an exception


!MESSAGE TreeWalk has not been set
!STACK 0
java.lang.IllegalStateException: TreeWalk has not been set
	at org.eclipse.egit.ui.internal.history.CommitFileDiffViewer.getTreeWalk(CommitFileDiffViewer.java:384)
	at org.eclipse.egit.ui.internal.history.FileDiffContentProvider.inputChanged(FileDiffContentProvider.java:30)
	at org.eclipse.jface.viewers.ContentViewer.handleDispose(ContentViewer.java:171)
	at org.eclipse.jface.viewers.StructuredViewer.handleDispose(StructuredViewer.java:2302)
	at org.eclipse.jface.viewers.AbstractTableViewer.handleDispose(AbstractTableViewer.java:223)
	at org.eclipse.jface.viewers.ContentViewer$2.widgetDisposed(ContentViewer.java:214)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:3776)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1367)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1390)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1371)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1216)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:902)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1219)
	at org.eclipse.swt.widgets.Control.release(Control.java:2556)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:625)
	at org.eclipse.ui.internal.PartPane.dispose(PartPane.java:180)
	at org.eclipse.ui.internal.ViewPane.dispose(ViewPane.java:193)
	at org.eclipse.ui.internal.WorkbenchPartReference.dispose(WorkbenchPartReference.java:681)
	at org.eclipse.ui.internal.WorkbenchPage.disposePart(WorkbenchPage.java:1721)
	at org.eclipse.ui.internal.WorkbenchPage.partRemoved(WorkbenchPage.java:1713)
	at org.eclipse.ui.internal.ViewFactory.releaseView(ViewFactory.java:257)
	at org.eclipse.ui.internal.Perspective.dispose(Perspective.java:292)
	at org.eclipse.ui.internal.WorkbenchPage.dispose(WorkbenchPage.java:1792)
	at org.eclipse.ui.internal.WorkbenchWindow.closeAllPages(WorkbenchWindow.java:861)
	at org.eclipse.ui.internal.WorkbenchWindow.hardClose(WorkbenchWindow.java:1696)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:734)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:710)
	at org.eclipse.ui.internal.WorkbenchWindow$5.run(WorkbenchWindow.java:826)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:824)
	at org.eclipse.jface.window.WindowManager.close(WindowManager.java:109)
	at org.eclipse.ui.internal.Workbench$18.run(Workbench.java:1106)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1103)
	at org.eclipse.ui.internal.Workbench.access$15(Workbench.java:1032)
	at org.eclipse.ui.internal.Workbench$25.run(Workbench.java:1276)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1274)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1246)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:731)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:710)
	at org.eclipse.ui.internal.WorkbenchWindow$5.run(WorkbenchWindow.java:826)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:824)
	at org.eclipse.jface.window.Window.handleShellCloseEvent(Window.java:741)
	at org.eclipse.jface.window.Window$3.shellClosed(Window.java:687)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:98)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:3776)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1367)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1390)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1375)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:548)
	at org.eclipse.swt.widgets.Shell.windowShouldClose(Shell.java:2029)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4974)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:220)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:1943)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2025)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:4582)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:4659)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:115)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3274)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1383)

Patch-set: 1