Update patch set 2
Patch Set 2:

org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: The widget {(of type 'MenuItem' and with mnemonic 'Push')} was disposed.
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.<init>(AbstractSWTBot.java:106)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.<init>(SWTBotMenu.java:42)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot.contextMenu(AbstractSWTBot.java:460)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotTreeItem.contextMenu(SWTBotTreeItem.java:528)
	at org.eclipse.egit.ui.view.repositories.GitRepositoriesViewFetchAndPushTest.testPushToOrigin(GitRepositoriesViewFetchAndPushTest.java:101)

Why does it fail? I can execure this test a hundred times on my PC and it works. Perhaps something disturbs the UI and causes the context menu to disappear?

Patch-set: 2