Update patch set 9
Patch Set 9: I would prefer that you didn't submit this

rebased

the following tests fail on Mac OS X:


Rerun org.eclipse.egit.ui.view.synchronize.SynchronizeViewWorkspaceModelTest.shouldListFileDeletedChange
shouldListFileDeletedChange(org.eclipse.egit.ui.view.synchronize.SynchronizeViewWorkspaceModelTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:348)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:308)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1110)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1099)
	at org.eclipse.egit.ui.view.synchronize.SynchronizeViewWorkspaceModelTest.shouldListFileDeletedChange(SynchronizeViewWorkspaceModelTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:360)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:346)
	... 35 more

Rerun org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest.shouldListFileDeletedChange
shouldListFileDeletedChange(org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:348)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:308)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1110)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1099)
	at org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest.shouldListFileDeletedChange(SynchronizeViewGitChangeSetModelTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
...
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:360)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:346)
	... 35 more

Patch-set: 9