Update patch set 1
Patch Set 1: Code-Review-1

I tried this (on Mac) following your steps to reproduce,

due to the bad URL I get the following exception

rg.eclipse.jgit.errors.NoRemoteRepositoryException: https://github.com/msohnx/HealloWorld.git: https://github.com/msohnx/HealloWorld.git/info/refs?service=git-receive-pack not found
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:482)
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:387)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:155)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1250)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:189)
	at org.eclipse.egit.ui.internal.push.ConfirmationPage$2.run(ConfirmationPage.java:210)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

then an error dialog is opened showing the message "Can't connect to any URI:  ... receive-pack not found", clicked OK.

Then the confirmation page still shows this error message, but "Finish" is still enabled, PushBranchWizard.canFinish() wasn't called again.

Patch-set: 1
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Code-Review=-1