Update patch set 3
Patch Set 3: Verified-1

Latest patch does not deadlock anymore but I can't get the root cause of two test failures:

java.lang.AssertionError: expected:<false> but was:<true>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.egit.ui.common.ExistingOrNewPage.assertContents(ExistingOrNewPage.java:91)
	at org.eclipse.egit.ui.common.ExistingOrNewPage.assertContents(ExistingOrNewPage.java:69)
	at org.eclipse.egit.ui.wizards.share.SharingWizardTest.shareProjectWithAlreadyCreatedRepos(SharingWizardTest.java:227)

java.lang.AssertionError: expected:<false> but was:<true>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.egit.ui.common.ExistingOrNewPage.assertContents(ExistingOrNewPage.java:77)
	at org.eclipse.egit.ui.common.ExistingOrNewPage.assertContents(ExistingOrNewPage.java:69)
	at org.eclipse.egit.ui.common.ExistingOrNewPage.assertContents(ExistingOrNewPage.java:52)
	at org.eclipse.egit.ui.wizards.share.SharingWizardTest.shareProjectAndCreateRepo(SharingWizardTest.java:166)

Patch-set: 3
Label: Verified=-1