Update patch set 2
Patch Set 2:

The failure is

  !ENTRY org.eclipse.egit.ui 4 0 2021-11-23 11:48:31.305
  !MESSAGE https://127.0.0.1:46527/sbasic/test1637668109449.git: 400 Bad Request
  !STACK 0
  org.eclipse.jgit.api.errors.TransportException: https://127.0.0.1:46527/sbasic/test1637668109449.git: 400 Bad Request
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:189)
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:128)
	at org.eclipse.egit.core.op.ListRemoteOperation.run(ListRemoteOperation.java:116)
	at org.eclipse.egit.ui.internal.clone.SourceBranchPage$9.run(SourceBranchPage.java:377)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
  Caused by: org.eclipse.jgit.errors.TransportException: https://127.0.0.1:46527/sbasic/test1637668109449.git: 400 Bad Request
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:719)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465)
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:167)
	... 4 more

The file deletion failure is probably a follow-up problem.

Patch-set: 2