Update patch set 3
Patch Set 3:

Matthias,
I have a patch but I can't push because:
"You must be a committer to push on behalf of others."
"error: You are not a project committer.
error: Only project committers can push on behalf of others."
So what to do now?

Patch-set: 3