Update patch set 7
Patch Set 7:

Looks good, just two things:

1. Choosing an existing lightweight tag, not changing anything but setting the "Force overwrite" and then clicking "Create Tag" results in an error dialog and an exception being logged:

org.eclipse.team.core.TeamException: Tag newtag creation failed (cause: NO_CHANGE)
	at org.eclipse.egit.core.op.TagOperation.updateRepo(TagOperation.java:94)

updateRepo() should not throw an exception on NO_CHANGE.

2. There should be more tests:

* The above.
* Moving a lightweight tag. Test should verify that the tag points to the expected commit.
* Changing a lightweight tag into an annotated tag: choose existing lightweight tag, force overwrite, add message, create tag. Test should verify that tag is still on the same commit and has the expected message.
* Changing an annotated tag into a lightweight tag: choose existing annotated tag, force overwrite, clear message, create tag. Test should verify that tag is still on the same commit and is a lightweight tag.

Patch-set: 7