Update patch set 3
Patch Set 3: I would prefer that you didn't submit this

(1 inline comment)

when the push fails (e.g. when network connection is down) the error is only dumped to the error log, instead the error should be reported in an error dialog. Also the error message is wrong, I tried without network connection and got the following error message in the error log which is misleading (there is something to push but I can't since I can't connect to the upstream repository):

eclipse.buildId=unknown
java.version=1.6.0_33
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /Users/d029788/Documents/workspace/egit/../runtime-EGit -dev file:/Users/d029788/Documents/workspace/egit/.metadata/.plugins/org.eclipse.pde.core/EGit/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

Error
Sun Sep 02 23:48:04 CEST 2012
An exception occurred during push on URI https://git.eclipse.org/r/p/jgit/jgit.git: Nothing to push.

org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:157)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:226)
	at org.eclipse.egit.ui.internal.push.PushOperationUI.execute(PushOperationUI.java:145)
	at org.eclipse.egit.ui.internal.push.PushOperationUI$1.run(PushOperationUI.java:202)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1159)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:153)
	... 4 more

In addition the following error message is written to the error log without a stack trace:

Invalid preference page path: XML Syntax

Patch-set: 3