Update patch set 4
Patch Set 4: Looks good to me, approved; Unclean IP, do not check in

- added missing import for @RunWith annotation
- made EGitTestCase abstract to fix
java.lang.Exception: No runnable methods
        at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:171)

- this change needs a CQ hence marked unclean IP

Patch-set: 4