Update patch set 7
Patch Set 7: I would prefer that you didn't submit this; No score

I did a first quick try (will do more testing tomorrow) with a test copy of jgit, 
added some local commits to it and then ran synchronize to compare
local/HEAD against origin/master, 
that hit the following NPE:

org.eclipse.team.core.TeamException: An internal error occurred processing subscriber events.
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.processEvent(SubscriberEventHandler.java:332)
	at org.eclipse.team.internal.core.BackgroundEventHandler.processEvents(BackgroundEventHandler.java:369)
	at org.eclipse.team.internal.core.BackgroundEventHandler$1.run(BackgroundEventHandler.java:203)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
	at org.eclipse.egit.ui.internal.synchronize.GitResourceVariantTree.members(GitResourceVariantTree.java:98)
	at org.eclipse.egit.ui.internal.synchronize.GitResourceVariantTreeSubscriber.members(GitResourceVariantTreeSubscriber.java:74)
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.collect(SubscriberEventHandler.java:200)
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.processEvent(SubscriberEventHandler.java:310)
	... 3 more

Patch-set: 7