Don't try to store incomplete credentials in secure store
The Eclipse secure store throws the exception
org.eclipse.equinox.security.storage.StorageException: No password
provided
when EGit tries to store incomplete credentials (missing user or
password). Hence only attempt to store credentials if user and password
are both available.

Bug: 525769
Change-Id: Icfa2743a69bda2e82f8c1034976dfde0482731d5
Signed-off-by: Matthias Sohn <matthias.sohn@sap.com>