Update patch set 4
Patch Set 4: Looks good to me, approved; No score

SWTBot is running with helios, but p2 provisioning fails with ganymede.  Also, some tests fail on my desktop.  I'm not sure if its an existing test breakage, or something wrong with this build configuration.  Right now I'm thinking its just existing test breakage...

  invalidHostnameFreezesDialog(org.eclipse.egit.ui.wizards.clone.GitCloneWizardTest)  Time elapsed: 5.121 sec  <<< ERROR!
  org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
  Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find shell matching: with text 'Import'

Patch-set: 4