Update patch set 5
Patch Set 5: Verified-1

the new tests succeed when run from Eclipse but when run from Maven the following two tests are failing:

 Failed tests:    mergeNoConflict(org.eclipse.egit.core.synchronize.GitSubscriberMergeContextTest): expected:<0> but was:<4>
   
 mergeModelNoConflict(org.eclipse.egit.core.synchronize.GitSubscriberMergeContextTest): expected:<0> but was:<4>

in mergeNoConflict() the following assertion 

 assertEquals(IStatus.OK, mergeStatus.getSeverity());

in line 179 fails with mergeStatus

 Status ERROR: org.eclipse.team.core code=1 No storage merger could be found to merge the input null

in mergeModelNoConflict() the assertion

 assertEquals(IStatus.OK, mergeStatus.getSeverity()); in line 236
 
fails with mergeStatus
 
 Status ERROR: org.eclipse.team.core code=1 Some conflicting changes cannot be merged automatically. These changes will have to be merged manually. null 

looks like some prerequisite is missing when running the tests from Maven

If you want to debug the test run from Maven run 

 mvn clean install -DdebugPort=8000

and attach the debugger at the specified port

Patch-set: 5
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=-1