Update patch set 3
Patch Set 3: Code-Review-1

With this change fetched, and "sync with selection" active in history view, I get exceptions when selecting very old tracking branches in platform.ui, like "origin/perf_33x".

org.eclipse.jgit.errors.MissingObjectException: Missing commit f65a2264da7635decdaa83e4e98baca11eb1e3c1
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:170)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:980)
	at org.eclipse.jgit.revwalk.RevCommit.parseBody(RevCommit.java:166)
	at org.eclipse.jgit.revwalk.RevWalk.parseBody(RevWalk.java:1111)
	at org.eclipse.egit.ui.internal.history.SWTCommit.parseBody(SWTCommit.java:47)
	at org.eclipse.egit.ui.internal.history.SWTPlotRenderer.paint(SWTPlotRenderer.java:130)
	at org.eclipse.egit.ui.internal.history.CommitGraphTable.doPaint(CommitGraphTable.java:555)
	at org.eclipse.egit.ui.internal.history.CommitGraphTable$8.handleEvent(CommitGraphTable.java:527)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Table.sendPaintItemEvent(Table.java:4115)
	at org.eclipse.swt.widgets.Table.CDDS_SUBITEMPOSTPAINT(Table.java:973)
	at org.eclipse.swt.widgets.Table.wmNotifyChild(Table.java:7047)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5825)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:2048)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5379)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4855)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2446)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:580)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:446)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4897)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:6037)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3822)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

!ENTRY org.eclipse.egit.ui 4 0 2019-07-07 15:38:00.468
!MESSAGE Missing unknown fd79c60347d5b980bc098ee94aaf4993dd82edb9
!STACK 0
org.eclipse.jgit.errors.MissingObjectException: Missing unknown fd79c60347d5b980bc098ee94aaf4993dd82edb9
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:168)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:236)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:936)
	at org.eclipse.jgit.revwalk.RevWalkUtils.findBranchesReachableFrom(RevWalkUtils.java:204)
	at org.eclipse.egit.ui.internal.history.CommitInfoBuilder.getBranches(CommitInfoBuilder.java:274)
	at org.eclipse.egit.ui.internal.history.CommitInfoBuilder.format(CommitInfoBuilder.java:125)
	at org.eclipse.egit.ui.internal.history.FormatJob.run(FormatJob.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 4 0 2019-07-07 15:38:00.487
!MESSAGE Can't get file difference of commit 0ae08bb90ac3fe458d507ed371b3221df4f4c4e7 1561132748 -----p.
!STACK 0
org.eclipse.jgit.errors.MissingObjectException: Missing tree 6c2de78f12b698ea10e3aa5395d12562c5a3fdc1
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:170)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:224)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator0(CanonicalTreeParser.java:259)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:237)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:1)
	at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:1303)
	at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:859)
	at org.eclipse.jgit.diff.DiffEntry.scan(DiffEntry.java:188)
	at org.eclipse.egit.ui.internal.history.FileDiff.compute(FileDiff.java:161)
	at org.eclipse.egit.ui.internal.history.FileDiff.compute(FileDiff.java:119)
	at org.eclipse.egit.ui.internal.history.CommitFileDiffViewer$FileDiffLoader.run(CommitFileDiffViewer.java:756)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 4 0 2019-07-07 15:38:00.720
!MESSAGE Missing commit 235f6c4cc79b51d741409c440e3d65f01747a0e2
!STACK 0
org.eclipse.jgit.errors.MissingObjectException: Missing commit 235f6c4cc79b51d741409c440e3d65f01747a0e2
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:170)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:980)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:159)
	at org.eclipse.jgit.revwalk.MergeBaseGenerator._next(MergeBaseGenerator.java:154)
	at org.eclipse.jgit.revwalk.MergeBaseGenerator.init(MergeBaseGenerator.java:109)
	at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:105)
	at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:464)
	at org.eclipse.jgit.revwalk.RevWalk.isMergedInto(RevWalk.java:438)
	at org.eclipse.jgit.revwalk.RevWalkUtils.findBranchesReachableFrom(RevWalkUtils.java:215)
	at org.eclipse.egit.ui.internal.history.CommitInfoBuilder.getBranches(CommitInfoBuilder.java:274)
	at org.eclipse.egit.ui.internal.history.CommitInfoBuilder.format(CommitInfoBuilder.java:125)
	at org.eclipse.egit.ui.internal.history.FormatJob.run(FormatJob.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Patch-set: 3
Label: Code-Review=-1