Update patch set 1
Patch Set 1:

I get an ClassCastException when I try to lunch compare editor for file that does not have base or remote variant (was added or deleted)

java.lang.ClassCastException: org.eclipse.egit.ui.internal.GitCompareFileRevisionEditorInput$EmptyTypedElement cannot be cast to org.eclipse.egit.ui.internal.FileRevisionTypedElement
at org.eclipse.egit.ui.internal.synchronize.model.GitModelBlob.prepareInput(GitModelBlob.java:150)
at org.eclipse.team.internal.ui.mapping.ModelCompareEditorInput.prepareCompareInput(ModelCompareEditorInput.java:121)
at org.eclipse.team.ui.synchronize.SaveableCompareEditorInput.prepareInput(SaveableCompareEditorInput.java:235)
at org.eclipse.compare.CompareEditorInput.run(CompareEditorInput.java:483)
at org.eclipse.compare.internal.CompareUIPlugin.prepareInput(CompareUIPlugin.java:548)
at org.eclipse.compare.internal.CompareEditor$2.run(CompareEditor.java:349)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Patch-set: 1