Update patch set 3
Patch Set 3: I would prefer that you didn't submit this

(1 inline comment)

- When first select "Checkout FETCH_HEAD" or "Update FETCH_HEAD only", select the checkbox and then again select one of the other options which hide the checkbox, after finish the preference is changed nevertheless, which comes as a surprise.
- I get an exception when I select the checkbox and then press "Finish".

org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4282)
	at org.eclipse.swt.SWT.error(SWT.java:4197)
	at org.eclipse.swt.SWT.error(SWT.java:4168)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:468)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:359)
	at org.eclipse.swt.widgets.Table.deselectAll(Table.java:1966)
	at org.eclipse.jface.viewers.TableViewer.doDeselectAll(TableViewer.java:277)
	at org.eclipse.jface.viewers.AbstractTableViewer.setSelectionToWidget(AbstractTableViewer.java:880)
	at org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1769)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1450)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1404)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1506)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1465)
	at org.eclipse.egit.ui.internal.history.GitHistoryPage.setupFileViewer(GitHistoryPage.java:1734)
	at org.eclipse.egit.ui.internal.history.GitHistoryPage.initAndStartRevWalk(GitHistoryPage.java:1519)
	at org.eclipse.egit.ui.internal.history.GitHistoryPage.inputSet(GitHistoryPage.java:1210)
	at org.eclipse.egit.ui.internal.history.GitHistoryPage.refresh(GitHistoryPage.java:1025)
	at org.eclipse.egit.ui.internal.history.GitHistoryPage$GitHistoryPageActions$5.apply(GitHistoryPage.java:381)
	at org.eclipse.egit.ui.internal.history.GitHistoryPage$GitHistoryPageActions$BooleanPrefAction.propertyChange(GitHistoryPage.java:148)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$3.run(ScopedPreferenceStore.java:375)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:372)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:813)
	at org.eclipse.egit.ui.internal.fetch.FetchGerritChangePage$10.run(FetchGerritChangePage.java:518)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

Patch-set: 3