Update patch set 5
Patch Set 5:

> I tried to run the test you ignored. It seems to fail when
 > selecting the cloned repository via swtbot. I always get an NPE at
 > this step:
 > 
 > java.lang.NullPointerException: while trying to invoke the method
 > org.eclipse.core.runtime.dynamichelpers.IExtensionTracker.registerHandler(org.eclipse.core.runtime.dynamichelpers.IExtensionChangeHandler,
 > org.eclipse.core.runtime.dynamichelpers.IFilter) of a null object
 > loaded from local variable 'tracker'
 > at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.<init>(StatusHandlerRegistry.java:72)
 > ...
 > at org.eclipse.core.internal.resources.Workspace.close(Workspace.java:575)
 > ...

No, that's the SWTBot runtime Eclipse shutting down at the end of the test. I have been getting that always when I run tests locally. It can be safely ignored. If the JUnit test runs green, it is fine; if it is red, it didn't work.

I tried now on two different machines (Mac 10.7.5 (JDK 8u65, using Neon target; started from a Neon.3) and 10.9.5 (JDK 8u131; using Oxygen target; started from Neon.2); and on both I now need to add this Djava.awt.headless=true to get _any_ SWTBot to run at all. Maybe it's time to upgrade to the latest OS X...).

Otherwise they deadlock in native classloader code when loading the AWT libraries, which happens inside SWTBot when it tries to figure out what keyboard we have; via the init of EGitTestCase.bot = new SWTWorkbenchBot(). Perhaps doing that statically is not such a good idea; what if the workbench isn't running yet?

Patch-set: 5