Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> The failure is
> 
>   !ENTRY org.eclipse.egit.ui 4 0 2021-11-23 11:48:31.305
>   !MESSAGE https://127.0.0.1:46527/sbasic/test1637668109449.git: 400 Bad Request
>   !STACK 0
>   org.eclipse.jgit.api.errors.TransportException: https://127.0.0.1:46527/sbasic/test1637668109449.git: 400 Bad Request
> 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:189)
> 	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:128)
> 	at org.eclipse.egit.core.op.ListRemoteOperation.run(ListRemoteOperation.java:116)
> 	at org.eclipse.egit.ui.internal.clone.SourceBranchPage$9.run(SourceBranchPage.java:377)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
>   Caused by: org.eclipse.jgit.errors.TransportException: https://127.0.0.1:46527/sbasic/test1637668109449.git: 400 Bad Request
> 	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:719)
> 	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465)
> 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:167)
> 	... 4 more
> 
> The file deletion failure is probably a follow-up problem.

ok, if it's 400 Bad Request it could be a similar problem I had with jgit https tests
which were caused by Jetty 10 being more strict with SNI validation. See
https://git.eclipse.org/r/c/jgit/jgit/+/187918/7/org.eclipse.jgit.junit.http/src/org/eclipse/jgit/junit/http/AppServer.java

If you can reproduce the problem add an exception breakpoint on org.eclipse.jetty.http.BadMessageException to find the place where it occurs. Took me a couple of hours to find this in Jetty.

Patch-set: 2
Reviewer: Gerrit User 4 <4@97ee7c02-f12f-4043-b43e-dea463d88b31>