Update patch set 11
Patch Set 11: I would prefer that you didn't submit this

- tests are succeeding now :-)

- when synchronizing a commit with its immediate predecessor in the history the synchronize view shows the differing files as conflicting, this seems wrong

- I hit the following exceptions:

eclipse.buildId=I20110603-0909
java.version=1.6.0_26
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.sdk.ide
Command-line arguments:  -product org.eclipse.sdk.ide -data /Users/d029788/Documents/workspace/egit/../runtime-EGit(Indigo) -dev file:/Users/d029788/Documents/workspace/egit/.metadata/.plugins/org.eclipse.pde.core/EGit/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

Error
Sun Aug 21 00:04:14 CEST 2011
There is no cached contents for resource org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/commit/CommitEditor.java.

org.eclipse.team.core.TeamException: There is no cached contents for resource org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/commit/CommitEditor.java.
	at org.eclipse.team.core.variants.CachedResourceVariant$ResourceVariantStorage.getContents(CachedResourceVariant.java:63)
	at org.eclipse.egit.core.synchronize.GitResourceVariantComparator.compare(GitResourceVariantComparator.java:54)
	at org.eclipse.team.core.synchronize.SyncInfo.calculateKind(SyncInfo.java:432)
	at org.eclipse.team.core.synchronize.SyncInfo.init(SyncInfo.java:401)
	at org.eclipse.egit.core.synchronize.GitResourceVariantTreeSubscriber.getSyncInfo(GitResourceVariantTreeSubscriber.java:200)
	at org.eclipse.team.core.variants.ResourceVariantTreeSubscriber.getSyncInfo(ResourceVariantTreeSubscriber.java:59)
	at org.eclipse.team.core.subscribers.Subscriber.getDiff(Subscriber.java:371)
	at org.eclipse.team.internal.core.subscribers.SubscriberDiffTreeEventHandler.handleChange(SubscriberDiffTreeEventHandler.java:162)
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.collect(SubscriberEventHandler.java:219)
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.processEvent(SubscriberEventHandler.java:310)
	at org.eclipse.team.internal.core.BackgroundEventHandler.processEvents(BackgroundEventHandler.java:369)
	at org.eclipse.team.internal.core.BackgroundEventHandler$1.run(BackgroundEventHandler.java:203)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

eclipse.buildId=I20110603-0909
java.version=1.6.0_26
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.sdk.ide
Command-line arguments:  -product org.eclipse.sdk.ide -data /Users/d029788/Documents/workspace/egit/../runtime-EGit(Indigo) -dev file:/Users/d029788/Documents/workspace/egit/.metadata/.plugins/org.eclipse.pde.core/EGit/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

Error
Sun Aug 21 00:12:59 CEST 2011
An internal error occurred processing subscriber events.

org.eclipse.team.core.TeamException: An internal error occurred processing subscriber events.
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.processEvent(SubscriberEventHandler.java:332)
	at org.eclipse.team.internal.core.BackgroundEventHandler.processEvents(BackgroundEventHandler.java:369)
	at org.eclipse.team.internal.core.BackgroundEventHandler$1.run(BackgroundEventHandler.java:203)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
	at org.eclipse.egit.core.synchronize.GitSyncObjectCache.get(GitSyncObjectCache.java:135)
	at org.eclipse.egit.core.synchronize.GitResourceVariantTree.fetchVariant(GitResourceVariantTree.java:101)
	at org.eclipse.egit.core.synchronize.GitResourceVariantTree.fetchVariant(GitResourceVariantTree.java:80)
	at org.eclipse.egit.core.synchronize.GitResourceVariantTree.getResourceVariant(GitResourceVariantTree.java:147)
	at org.eclipse.team.core.variants.ResourceVariantTreeSubscriber.getSyncInfo(ResourceVariantTreeSubscriber.java:52)
	at org.eclipse.team.core.subscribers.Subscriber.getDiff(Subscriber.java:371)
	at org.eclipse.team.internal.core.subscribers.SubscriberDiffTreeEventHandler.handleChange(SubscriberDiffTreeEventHandler.java:162)
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.collect(SubscriberEventHandler.java:219)
	at org.eclipse.team.internal.core.subscribers.SubscriberEventHandler.processEvent(SubscriberEventHandler.java:310)
	... 3 more

Patch-set: 11