Update patch set 5
Patch Set 5: I would prefer that you didn't submit this

- rebased and resolved conflicts
- fixed dependency problem by declaring the egit.mylyn.ui plugin x-friend of the egit.ui plugin

- the action "Open Corresponding Task" fails with

!MESSAGE Problem while parsing task id from comment
!STACK 0
java.lang.IndexOutOfBoundsException: No group 1
	at java.util.regex.Matcher.group(Matcher.java:470)
	at org.eclipse.mylyn.internal.team.ui.templates.CommitTemplateManager.getTaskIdFromCommentOrLabel(CommitTemplateManager.java:74)
	at org.eclipse.mylyn.internal.team.ui.actions.TaskFinder.reconcile(TaskFinder.java:174)
	at org.eclipse.mylyn.internal.team.ui.actions.TaskFinder.initialize(TaskFinder.java:239)
	at org.eclipse.mylyn.internal.team.ui.actions.TaskFinder.<init>(TaskFinder.java:215)
	at org.eclipse.mylyn.internal.team.ui.actions.OpenCorrespondingTaskAction.run(OpenCorrespondingTaskAction.java:66)
	at org.eclipse.mylyn.internal.team.ui.actions.OpenCorrespondingTaskAction.run(OpenCorrespondingTaskAction.java:58)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:251)

for the commit message notation we use in the egit project (Bug: footer in last paragraph of commit message)

Patch-set: 5