Update patch set 2
Patch Set 2: I would prefer that you didn't submit this

(11 inline comments)

I cannot see the difference between a directory/submodule/repo and a file in the dialog.


This following failed. old is a directory with a .git directory inside it.. C Git does not clean it (though is says it does). In this case it is a nested repo, but we could have submodules. But should be handled nicely, Don't delete and tell the user in a decipherable way.


org.eclipse.jgit.api.errors.JGitInternalException: Could not delete file /Users/me/SW/myegit/JGIT/old
at org.eclipse.jgit.api.CleanCommand.call(CleanCommand.java:97)
at org.eclipse.egit.core.op.CleanOperation.execute(CleanOperation.java:74)
at org.eclipse.egit.core.internal.job.JobUtil$1.run(JobUtil.java:50)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: Could not delete file /Users/me/SW/myegit/JGIT/old
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:134)
at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:92)
at org.eclipse.jgit.api.CleanCommand.call(CleanCommand.java:92)
... 3 more

Patch-set: 2