Update patch set 6
Patch Set 6: I would prefer that you didn't submit this

this seems not to work, I still see tags not pointing to commits, when trying to synchronize on these I hit:

org.eclipse.jgit.errors.IncorrectObjectTypeException: Object 8bbde7aacf771a9afb6992434f1ae413e010c6d8 is not a commit.
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:726)
	at org.eclipse.egit.core.synchronize.dto.GitSynchronizeData.<init>(GitSynchronizeData.java:84)
	at org.eclipse.egit.ui.internal.actions.SynchronizeWithMenu$1.widgetSelected(SynchronizeWithMenu.java:147)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
...

also the menu label should be changed to "Synchronize" (without "...") as it doesn't open a dialog or wizard but the dynamic submenu

Patch-set: 6