Update patch set 3
Patch Set 3:

I setup a local Gerrit 2.15.2 server including lfs plugin from stable-2.15, added the following configuration to the lfs.config file of the refs/meta/config branch of the All-Projects project

 [lfs "?/*"]
   enabled = true
   maxObjectSize = 500m

cloned the repository, added .gitattributes for tracking pdf files in lfs, successfully pushed and merged this change. Then I created a.pdf used this Egit version to create a commit, it's properly stored in lfs. Though pushing that commit to this Gerrit instance also yields 401 both using http or ssh. I configured lfs.url=http://admin@localhost:8080/a/lfsdemo/info/lfs in the local repository.

org.eclipse.jgit.errors.TransportException: When trying to open a connection to http://admin@localhost:8080/a/lfsdemo/info/lfs/objects/batch the server responded with an error code. rc=401
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1341)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:191)
	at org.eclipse.egit.ui.internal.push.PushJob.performJob(PushJob.java:86)
	at org.eclipse.egit.ui.internal.jobs.RepositoryJob.run(RepositoryJob.java:59)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.io.IOException: When trying to open a connection to http://admin@localhost:8080/a/lfsdemo/info/lfs/objects/batch the server responded with an error code. rc=401
	at org.eclipse.jgit.lfs.LfsPrePushHook.requestBatchUpload(LfsPrePushHook.java:214)
	at org.eclipse.jgit.lfs.LfsPrePushHook.call(LfsPrePushHook.java:123)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1339)
	... 4 more

Patch-set: 3
Label: Verified=0