Update patch set 3
Patch Set 3: I would prefer that you didn't submit this; No score

This implements tag -a, right ? Lightweight and signed tags are not yet supported.
I think you should mention that in the commit message.

The layout of the BranchSelectionDialog sucks, buttons have random size
and are distributed randomly on the dialog. Your new button "New tag" follows 
this bad tradition ...See http://egit.eclipse.org/r/#change,578
which intends to improve that. 

What about deleting a tag ?

Tagging of non-HEAD commits isn't yet possible, right ?

Wouldn't it be a good idea to also allow editing the tag message when renaming a tag ?
This would be something like tag -f from command line git.

Show Resource history is broken by your change :
- create a tag
- in package explorer select some file and Team > Show in Resource History
this throws :
java.lang.NumberFormatException: For input string: "1761820 +0200"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
at java.lang.Integer.parseInt(Integer.java:458)
at java.lang.Integer.parseInt(Integer.java:499)
at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:220)
at org.eclipse.jgit.lib.Tag.decode(Tag.java:161)
at org.eclipse.jgit.lib.Tag.getTagger(Tag.java:242)
at org.eclipse.jgit.revplot.PlotWalk$PlotRefComparator.timeof(PlotWalk.java:135)
at org.eclipse.jgit.revplot.PlotWalk$PlotRefComparator.compare(PlotWalk.java:120)
at org.eclipse.jgit.revplot.PlotWalk$PlotRefComparator.compare(PlotWalk.java:1)
at java.util.Arrays.mergeSort(Arrays.java:1270)
at java.util.Arrays.sort(Arrays.java:1210)
at org.eclipse.jgit.revplot.PlotWalk.getTags(PlotWalk.java:109)
at org.eclipse.egit.ui.internal.history.SWTWalk.createCommit(SWTWalk.java:23)
at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:736)
at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:660)
at org.eclipse.egit.ui.internal.history.GitHistoryPage.inputSet(GitHistoryPage.java:908)
at org.eclipse.team.ui.history.HistoryPage.setInput(HistoryPage.java:59)
at org.eclipse.egit.ui.internal.history.GitHistoryPage.setInput(GitHistoryPage.java:831)
at org.eclipse.team.internal.ui.history.GenericHistoryView.showHistoryPageFor(GenericHistoryView.java:738)
at org.eclipse.team.internal.ui.history.GenericHistoryView.showHistory(GenericHistoryView.java:969)
at org.eclipse.team.internal.ui.history.GenericHistoryView.access$3(GenericHistoryView.java:965)
at org.eclipse.team.internal.ui.history.GenericHistoryView$3.selectionChanged(GenericHistoryView.java:433)
at org.eclipse.ui.internal.AbstractSelectionService.firePostSelection(AbstractSelectionService.java:179)
at org.eclipse.ui.internal.AbstractSelectionService.setActivePart(AbstractSelectionService.java:289)
at org.eclipse.ui.internal.WorkbenchPagePartList.fireActivePartChanged(WorkbenchPagePartList.java:60)
at org.eclipse.ui.internal.PartList.setActivePart(PartList.java:136)
at org.eclipse.ui.internal.WorkbenchPage.setActivePart(WorkbenchPage.java:3537)
at org.eclipse.ui.internal.WorkbenchPage.requestActivation(WorkbenchPage.java:3077)
at org.eclipse.ui.internal.PartPane.requestActivation(PartPane.java:279)
at org.eclipse.ui.internal.PartPane.handleEvent(PartPane.java:237)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1050)

Patch-set: 3