Update patch set 6
Patch Set 6: I would prefer that you didn't submit this

(2 inline comments)

I can confirm that tests works also on Linux, but from time to time I got this  stacktrace in console:

org.eclipse.team.core.TeamException: An internal error occurred
	at org.eclipse.egit.core.op.CommitOperation.commit(CommitOperation.java:282)
	at org.eclipse.egit.ui.internal.staging.StagingView$23.commit(StagingView.java:1083)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:207)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1975)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1957)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:217)
	at org.eclipse.egit.ui.internal.commit.CommitUI$2.run(CommitUI.java:217)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Updating the ref HEAD to AnyObjectId[b8bb29aedb7b15139140d345be6b1ba8285e8461] failed. ReturnCode from RefUpdate.update() was NO_CHANGE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:247)
	at org.eclipse.egit.core.op.CommitOperation.commit(CommitOperation.java:271)
	... 7 more
!SUBENTRY 1 org.eclipse.team.core 4 0 2011-06-12 16:37:46.931
!MESSAGE An internal error occurred
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Updating the ref HEAD to AnyObjectId[b8bb29aedb7b15139140d345be6b1ba8285e8461] failed. ReturnCode from RefUpdate.update() was NO_CHANGE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:247)
	at org.eclipse.egit.core.op.CommitOperation.commit(CommitOperation.java:271)
	at org.eclipse.egit.ui.internal.staging.StagingView$23.commit(StagingView.java:1083)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:207)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1975)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1957)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:217)
	at org.eclipse.egit.ui.internal.commit.CommitUI$2.run(CommitUI.java:217)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

But it doesn't hit test results, they are still green ... odd.

Patch-set: 6