Update patch set 5
Patch Set 5: I would prefer that you didn't submit this

(15 inline comments)

the UI tests reported the following problems on Mac OS X, on current master they succeed without any error :

AllTests
org.eclipse.egit.ui.test.AllTests
org.eclipse.egit.ui.test.AllLocalTests
org.eclipse.egit.ui.view.synchronize.SynchronizeViewWorkspaceModelTest
shouldListFileDeletedChange(org.eclipse.egit.ui.view.synchronize.SynchronizeViewWorkspaceModelTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:348)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:308)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1110)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1099)
	at org.eclipse.egit.ui.view.synchronize.SynchronizeViewWorkspaceModelTest.shouldListFileDeletedChange(SynchronizeViewWorkspaceModelTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
	at java.lang.Thread.run(Thread.java:680)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:360)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:346)
	... 51 more

org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest
shouldListFileDeletedChange(org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:348)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.widget(SWTBotFactory.java:308)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1110)
	at org.eclipse.swtbot.swt.finder.SWTBot.tree(SWTBot.java:1099)
	at org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest.shouldListFileDeletedChange(SynchronizeViewGitChangeSetModelTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find widget matching: (of type 'Tree')
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:360)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:346)
	... 51 more

shouldSynchronizeInEmptyRepository(org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest)
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: null
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.egit.ui.test.TestUtil.waitUntilTreeHasNodeContainsText(TestUtil.java:182)
	at org.eclipse.egit.ui.view.synchronize.AbstractSynchronizeViewTest.waitForNodeWithText(AbstractSynchronizeViewTest.java:253)
	at org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest.shouldSynchronizeInEmptyRepository(SynchronizeViewGitChangeSetModelTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...

Patch-set: 5