Update patch set 13
Patch Set 13: I would prefer that you didn't submit this

still failing on Mac, I invite you to test this on my Mac ;-)


org.eclipse.egit.ui--All-SWT-Tests
org.eclipse.egit.ui.test.AllTests
org.eclipse.egit.ui.test.AllLocalTests
org.eclipse.egit.ui.test.team.actions.AllTeamActionTests
org.eclipse.egit.ui.test.team.actions.CompareActionsTest
testCompareWithPreviousWithMerge(org.eclipse.egit.ui.test.team.actions.CompareActionsTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:348)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shells(SWTBotFactory.java:112)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shell(SWTBotFactory.java:102)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shell(SWTBotFactory.java:93)
	at org.eclipse.egit.ui.test.team.actions.CompareActionsTest.testCompareWithPreviousWithMerge(CompareActionsTest.java:179)
...
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find shell matching: with text 'Commit Selection'
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:360)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:346)
	... 59 more

org.eclipse.egit.ui.test.team.actions.ReplaceActionsTest
testReplaceWithPreviousWithMerge(org.eclipse.egit.ui.test.team.actions.ReplaceActionsTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find widget.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:348)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shells(SWTBotFactory.java:112)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shell(SWTBotFactory.java:102)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.shell(SWTBotFactory.java:93)
	at org.eclipse.egit.ui.test.team.actions.ReplaceActionsTest.testReplaceWithPreviousWithMerge(ReplaceActionsTest.java:130)
...
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find shell matching: with text 'Commit Selection'
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:360)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:346)
	... 59 more

org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest
shouldExchangeCompareEditorSidesBetweenIncomingAndOutgoingChanges(org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest)
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: null
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:398)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:372)
	at org.eclipse.egit.ui.test.TestUtil.waitUntilTreeHasNodeContainsText(TestUtil.java:188)
	at org.eclipse.egit.ui.view.synchronize.AbstractSynchronizeViewTest.waitForNodeWithText(AbstractSynchronizeViewTest.java:281)
	at org.eclipse.egit.ui.view.synchronize.AbstractSynchronizeViewTest.getCompareEditorForFileInGitChangeSet(AbstractSynchronizeViewTest.java:260)
	at org.eclipse.egit.ui.view.synchronize.SynchronizeViewGitChangeSetModelTest.shouldExchangeCompareEditorSidesBetweenIncomingAndOutgoingChanges(SynchronizeViewGitChangeSetModelTest.java:217)

Patch-set: 13