Update patch set 3
Patch Set 3: I would prefer that you didn't submit this

- rebased to current master
- fixed a typo
- I like the feature :-)

- are the test adjustments a direct consequence of introducing the feature implemented here ?

- ui tests aren't stable on MacOSX, I ran them 4 times, they only succeeded once, here the failures for the other 3 runs:

#1:
testPushToOrigin(org.eclipse.egit.ui.view.repositories.GitRepositoriesViewFetchAndPushTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu: [Push]
	at org.eclipse.egit.ui.test.ContextMenuHelper.clickContextMenu(ContextMenuHelper.java:67)
	at org.eclipse.egit.ui.view.repositories.GitRepositoriesViewFetchAndPushTest.testPushToOrigin(GitRepositoriesViewFetchAndPushTest.java:150)

org.eclipse.egit.ui.test.history.HistoryViewTest
testOpenHistoryOnFileFolderFilter(org.eclipse.egit.ui.test.history.HistoryViewTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu: [Show In, History]
	at org.eclipse.egit.ui.test.ContextMenuHelper.clickContextMenu(ContextMenuHelper.java:67)
	at org.eclipse.egit.ui.test.history.HistoryViewTest.getHistoryViewTable(HistoryViewTest.java:256)
	at org.eclipse.egit.ui.test.history.HistoryViewTest.testOpenHistoryOnFileFolderFilter(HistoryViewTest.java:167)

#2:
testCreateDeleteLocalBranchWithUnmerged(org.eclipse.egit.ui.view.repositories.GitRepositoriesViewBranchHandlingTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu: [Checkout]
	at org.eclipse.egit.ui.test.ContextMenuHelper.clickContextMenu(ContextMenuHelper.java:67)
	at org.eclipse.egit.ui.view.repositories.GitRepositoriesViewBranchHandlingTest.testCreateDeleteLocalBranchWithUnmerged(GitRepositoriesViewBranchHandlingTest.java:205)

#3:
testCreateDeleteLocalBranchWithUnmerged(org.eclipse.egit.ui.view.repositories.GitRepositoriesViewBranchHandlingTest)
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu: [Checkout]
	at org.eclipse.egit.ui.test.ContextMenuHelper.clickContextMenu(ContextMenuHelper.java:67)
	at org.eclipse.egit.ui.view.repositories.GitRepositoriesViewBranchHandlingTest.testCreateDeleteLocalBranchWithUnmerged(GitRepositoriesViewBranchHandlingTest.java:205)

- please also verify on Linux to prevent that we destabilize ui tests

Patch-set: 3