Update patch set 6
Patch Set 6:

The build has failed because of
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]

Could somebody retrigger the build please? I don't know if there's anything else to do for this kind of error.

Patch-set: 6
Label: Verified=0