Update patch set 3
Patch Set 3:

> OK. Along with https://git.eclipse.org/r/#/c/124355/ things should
 > work nicely now against Gerrit (SSH) and GitHub (both SSH and
 > HTTPS).
 > 
 > I don't have a Gerrit instance with HTTPs and LFS support enabled
 > at hand, we only use SSH...

cloning from Github now works, though when trying to push a commit containing an LFS object over https I get 401:

org.eclipse.jgit.errors.TransportException: When trying to open a connection to https://github.com/msohn/lfsdemo.git/info/lfs/objects/batch the server responded with an error code. rc=401
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1341)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:191)
	at org.eclipse.egit.ui.internal.push.ConfirmationPage$2.run(ConfirmationPage.java:211)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.io.IOException: When trying to open a connection to https://github.com/msohn/lfsdemo.git/info/lfs/objects/batch the server responded with an error code. rc=401
	at org.eclipse.jgit.lfs.LfsPrePushHook.requestBatchUpload(LfsPrePushHook.java:214)
	at org.eclipse.jgit.lfs.LfsPrePushHook.call(LfsPrePushHook.java:123)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1339)
	... 3 more

same scenario pushing commit with LFS object to Github over SSH works nicely.

Will try with Gerrit and LFS plugin next.

Patch-set: 3