Update patch set 4
Patch Set 4:

In Eclipse I was trying to run the tests using swtbot, this was causing my test failures.

I keep getting the following error when running the new tests from maven on Max OS X :


[INFO] ------------------------------------------------------------------------
[INFO] Building EGit Mylyn UI Test Plug-in 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Deleting /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target
[INFO] 
[INFO] --- tycho-packaging-plugin:0.12.0:build-qualifier (default-build-qualifier) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] 
[INFO] --- tycho-packaging-plugin:0.12.0:validate-version (default-validate-version) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] 
[INFO] --- maven-resources-plugin:2.4.1:resources (default-resources) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Using 'ISO-8859-1' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/src/main/resources
[INFO] 
[INFO] --- tycho-compiler-plugin:0.12.0:compile (default-compile) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Using compile source roots from build.properties
[INFO] Compiling 2 source files to /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/classes

[INFO] 
[INFO] --- maven-resources-plugin:2.4.1:testResources (default-testResources) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Using 'ISO-8859-1' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/src/test/resources
[INFO] 
[INFO] --- tycho-compiler-plugin:0.12.0:testCompile (default-testCompile) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Using compile source roots from build.properties
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.7.2:test (default) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Surefire report directory: /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.egit.internal.mylyn.AllMylynTests
2011-08-17 11:00:10.243 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10210abd0 of class NSCFString autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.247 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x102402cc0 of class NSCFNumber autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.247 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x102407410 of class NSCFString autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.258 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10240f030 of class NSPathStore2 autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.258 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10240f1e0 of class NSPathStore2 autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.258 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x7fff70e29fb0 of class NSCFString autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.258 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10240ed70 of class NSCFString autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.259 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10240eaf0 of class NSCFData autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.264 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10210fe30 of class NSCFDictionary autoreleased with no pool in place - just leaking
2011-08-17 11:00:10.264 java[4051:1303] *** __NSAutoreleaseNoPool(): Object 0x10210fc10 of class __NSFastEnumerationEnumerator autoreleased with no pool in place - just leaking
[... a lot more lines like these ...]

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.025 sec

Results :

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- tycho-packaging-plugin:0.12.0:package-plugin (default-package-plugin) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Building jar: /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/org.eclipse.egit.mylyn.ui.test-1.1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- tycho-p2-plugin:0.12.0:p2-metadata (default-p2-metadata) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] 
[INFO] --- tycho-surefire-plugin:0.12.0:test (default-test) @ org.eclipse.egit.mylyn.ui.test ---
[INFO] Adding repository (cached) file://Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/../org.eclipse.egit-updatesite/target/site
[INFO] Adding repository (cached) file://Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/../../jgit/org.eclipse.jgit.packaging/org.eclipse.jgit.updatesite/target/site
[INFO] Adding repository (cached) http://download.eclipse.org/releases/galileo
[INFO] Adding repository (cached) http://download.eclipse.org/technology/swtbot/galileo/dev-build/update-site
[INFO] Adding repository (cached) http://download.eclipse.org/tools/mylyn/update/weekly
[INFO] Adding repository (cached) http://download.eclipse.org/jetty/7.1.6.v20100715/repository/
[INFO] Adding repository (cached) http://download.eclipse.org/tools/orbit/downloads/drops/R20110523182458/repository
[INFO] Expected eclipse log file: /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/work/data/.metadata/.log
[INFO] Command line:
	/bin/sh -c cd /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test && /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -Dosgi.noShutdown=false -Dosgi.os=macosx -Dosgi.ws=cocoa -Dosgi.arch=x86_64 -Xmx512m -XX:MaxPermSize=256m -XstartOnFirstThread -jar /Users/d029788/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.0.201.R35x_v20090715/org.eclipse.equinox.launcher-1.0.201.R35x_v20090715.jar -data /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/work/data -dev file:/Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/dev.properties -install /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/work -configuration /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/work/configuration -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /Users/d029788/src/git/egit/org.eclipse.egit.mylyn.ui.test/target/surefire.properties -testApplication org.eclipse.ui.ide.workbench -product org.eclipse.sdk.ide

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.egit.internal.mylyn.AllMylynTests
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
initializationError(org.eclipse.egit.internal.mylyn.AllMylynTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Exception: No runnable methods
	at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:154)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:112)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:253)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:55)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:56)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:13)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.<init>(JUnit4TestSet.java:45)
	at org.apache.maven.surefire.junit4.JUnit4DirectoryTestSuite.createTestSet(JUnit4DirectoryTestSuite.java:56)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.locateTestSets(AbstractDirectoryTestSuite.java:96)
	at org.apache.maven.surefire.Surefire.createSuiteFromDefinition(Surefire.java:209)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:156)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:72)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:35)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3405)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3102)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:113)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:114)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:559)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:514)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1311)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1287)


Results :

Tests in error: 
  initializationError(org.eclipse.egit.internal.mylyn.AllMylynTests)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

Patch-set: 4