Update patch set 3
Patch Set 3: Code-Review-1

(1 comment)

found this problem:
- create new Java project
- share it with git team provider and create a repository
- click "init gitflow" (repository is still empty, HEAD doesn't exist yet)
- in "Initialize repository" dialog choose non-default master branch e.g. master1
- gitflow warns that this master branch doesn't exist and asks if I want to create it
- click yes
- this hits the following exception

 org.eclipse.egit.gitflow.WrongGitFlowStateException: Git flow repository may not be empty.
	at org.eclipse.egit.gitflow.GitFlowRepository.findHead(GitFlowRepository.java:147)
	at org.eclipse.egit.gitflow.ui.internal.dialogs.InitDialog.okPressed(InitDialog.java:281)
	... 62 more

- the error is not shown in an error dialog but ends up in the error log only, so I
  can't leave the "Initialize repository" dialog until I click "Cancel"
- if initializing a gitflow repository requires HEAD then the action "Init Git Flow"
  should be disabled if HEAD doesn't exist / repository is empty
- or "Init Git Flow" should work on empty repository
- don't know how native gitflow handles this

- if I first create an initial commit the dialog works and I can create the
non-standard "master1" branch but then I already have a "master" branch and
have to delete that (I want the non-standard master1 branch and why should I
also use a master branch ?), so it looks like it would be better to rename
master to master1 instead of creating both.

Patch-set: 3
Label: Code-Review=-1