Update patch set 3
Patch Set 3: I would prefer that you didn't submit this

- it seems checking the new option to suppress the result dialog doesn't suppress the push result dialog
- the log should give similar details as the result dialog shows
- I think the log shouldn't silently go into the error log but be shown in a git console, this would simplify to understand which actions were done, to make this really useful also other git commands should write an entry to this git console
- we need a way to re-enable showing the push result dialog -> I think we should add a preference for that
- it looks like the checkbox should be indented a bit more since it's very close to the dialog's border
- found the following exception in the log after trying this

!ENTRY org.eclipse.ui 4 0 2013-04-30 00:26:03.784
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4361)
	at org.eclipse.swt.SWT.error(SWT.java:4276)
	at org.eclipse.swt.SWT.error(SWT.java:4247)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:775)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:569)
	at org.eclipse.swt.widgets.Button.getSelection(Button.java:512)
	at org.eclipse.egit.ui.internal.push.PushResultDialog.buttonPressed(PushResultDialog.java:113)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListene

Patch-set: 3